### ISSUE TITLE
Refaktorizacija

### ISSUE THREAD

**Issue by DenisAlicic** [djanluka/FuzzyClassification#1]
Skoro svaki fajl za klasifikacije ima ponavljanje koda za ucitavanje i podelu podataka.

Izdvojte to u neki utils.py, definisite funkcije i samo ih pozivajte. :D

Mozete i deo za klasifikaciju izvuci u posebnu funciju i samo instancirati objekte (KNN, DecisionTree...) i prosledjivati objekat i mapu parametara za CV.

**Comment by djanluka** [comment]
Dodat je utils.py koji ucitava podatke i ispisuje rezultate klasifikacija. Svestan sam da po pravilima ne bi trebalo tek tako da se mesaju funkcije koje ne rade "slican posao" , ali da ne preterujemo sad sa lepotom, mislim da je akcenat na drugim stvarima. :D

Takodje, napravljen je zajednicki fajl za klasifikacionim algoritmima.
